# name: Runners Deployment

# # on:
# #   workflow_run:
# #     workflows: [CI]
# #     types: [completed]


# jobs:
#   dump_contexts_to_log:
#     if: ${{ github.event.repository.default_branch == github.event.workflow_run.head_branch && (github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'schedule') && github.event.workflow_run.conclusion == 'failure' }}
#     runs-on: ubuntu-latest
#     environment: protected
#     steps:
#       - name: Dump GitHub context
#         id: github_context_step
#         run: echo '${{ toJSON(github) }}'
#       - name: Echo head branch
#         run: echo '${{ github.event.workflow_run.head_branch }}'
#       - name: Echo default branch
#         run: echo '${{ github.event.repository.default_branch }}'
#       - name: send-slack-message
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_WEBHOOK: ${{ secrets.HOOK }}
#           SLACK_MESSAGE: ${{ format('Workflow "{0}" failed. Check why here{1} {2}', github.event.workflow.name, ':' , github.event.workflow_run.html_url) }}
#           SLACK_COLOR: '#990f02'
#           MSG_MINIMAL: 'commit'
#           SLACK_FOOTER: ''
#           SLACK_MSG_AUTHOR: 'Github Workflow Notifier'
#           SLACK_ICON_EMOJI: ':bell:'
#           SLACK_ICON: https://pbs.twimg.com/profile_images/1145956652635570176/jbru7OZG_400x400.jpg
#       # - name: Discord notification
#       #   env:
#       #     DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
#       #   uses: Ilshidur/action-discord@master
#       #   with:
#       #     args: ${{ format('Workflow "{0}" failed. Check why here{1} {2}', github.event.workflow.name, ':' , github.event.workflow_run.html_url) }}
#       # https://discordapp.com/api/webhooks/
#       # 1013059457275674634/
#       # FO55I3Yk1kmSr53G1c1MKDWx98FzqNhsqYB2Wlnj3SI2qnY0d-SnQRnp8k3wu2TzL87v

#       - name: send custom message with args
#         uses: appleboy/discord-action@master
#         with:
#           webhook_id: ${{ secrets.WEBHOOK_ID }}
#           webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
#           args: ${{ format('Workflow "{0}" failed. Check why here{1} {2}', github.event.workflow.name, ':' , github.event.workflow_run.html_url) }}
#           color: '#990f02'
#           avatar_url: https://pbs.twimg.com/profile_images/1145956652635570176/jbru7OZG_400x400.jpg
#           username: 'Github Workflow Notifier'